import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy-policy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Vynta" },
      { name: "description", content: "Vynta Privacy Policy. Learn how we collect, use, and protect your personal data." },
      { property: "og:title", content: "Privacy Policy — Vynta" },
      { property: "og:description", content: "Vynta Privacy Policy and data protection practices." },
    ],
  }),
  component: PrivacyPolicy,
});

function PrivacyPolicy() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-background text-foreground">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-x-0 top-0 h-[600px]"
        style={{ background: "var(--gradient-radial)" }}
      />

      <header className="relative z-20">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6">
          <Link to="/" className="flex items-center gap-2">
            <span className="grid h-8 w-8 place-items-center rounded-full border border-border bg-surface-elevated">
              <span className="h-2 w-2 rounded-full bg-primary shadow-[0_0_12px_var(--color-primary)]" />
            </span>
            <span className="font-display text-2xl">Vynta</span>
          </Link>
          <Link
            to="/"
            className="rounded-full border border-border bg-surface/60 px-4 py-2 text-sm text-foreground backdrop-blur-md transition hover:bg-secondary"
          >
            ← Back to Home
          </Link>
        </div>
      </header>

      <article className="relative z-10 mx-auto max-w-3xl px-6 pb-24 pt-12">
        <div className="mb-4 flex items-center gap-3 text-xs uppercase tracking-[0.22em] text-muted-foreground">
          <span className="h-px w-8 bg-border" />
          Legal
        </div>
        <h1 className="font-display text-4xl md:text-6xl">
          Privacy <em className="italic text-gradient">Policy</em>
        </h1>
        <p className="mt-6 leading-relaxed text-muted-foreground">
          At VyntaOne, we are deeply committed to protecting the privacy of our Clients and the callers who interact with our automated AI voice receptionists. This Privacy Policy outlines how we collect, use, process, disclose, and secure personal information processed through our systems and services.
        </p>

        <section className="mt-14">
          <h2 className="font-display text-2xl md:text-3xl">Categories of Personal Data Collected</h2>
          <p className="mt-6 text-muted-foreground">
            VyntaOne processes personal data of two categories of individuals: <strong className="text-foreground">Clients</strong> (the business owners subscribing to VyntaOne) and <strong className="text-foreground">Callers</strong> (individuals calling the Client's business phone lines).
          </p>

          <h3 className="mt-8 text-lg font-medium text-foreground">A. Client Data (Information We Collect About You)</h3>
          <div className="mt-4 space-y-5 text-muted-foreground">
            <p><strong className="text-foreground">Account Registration & Billing:</strong> Name, business name, physical address, billing address, email address, phone number, and transaction records. (All payment processing details are securely handled by our Merchant of Record, Paddle, and we do not store raw credit card numbers on our servers).</p>
            <p><strong className="text-foreground">Integration Credentials:</strong> API keys, access tokens, and calendar synchronization details (e.g., Cal.com, Google Calendar access permissions) provided to VyntaOne to facilitate direct scheduling.</p>
          </div>

          <h3 className="mt-8 text-lg font-medium text-foreground">B. Caller Data (Information Processed on Behalf of Our Clients)</h3>
          <div className="mt-4 space-y-5 text-muted-foreground">
            <p>When an individual calls a telephone number linked to a VyntaOne voice agent, we act as a Data Processor on behalf of our Client (the Data Controller). We collect and process:</p>
            <p><strong className="text-foreground">Call Metadata:</strong> Telephone numbers, call duration, timestamp, date, and call routing details.</p>
            <p><strong className="text-foreground">Audio Recordings & Transcripts:</strong> High-fidelity audio recordings of the call, as well as the text transcripts generated by our AI transcription services (e.g., Deepgram, OpenAI Whisper).</p>
            <p><strong className="text-foreground">In-Call Contextual Information:</strong> Personal information explicitly shared by callers during the conversation, such as their name, phone number, email address, business preferences, appointment dates, or service inquiries.</p>
          </div>
        </section>

        <section className="mt-14">
          <h2 className="font-display text-2xl md:text-3xl">Voice Recording, Processing, and Transcription Framework</h2>
          <div className="mt-6 space-y-5 text-muted-foreground">
            <p>Because VyntaOne provides an interactive, voice-driven service, recording and real-time processing of callers' voices are core operational requirements.</p>
            <p><strong className="text-foreground">How Voice is Processed:</strong> When a call is initiated, the caller's audio stream is transmitted securely to our speech-to-text (STT) engines. The synthesized text is evaluated by our large language models (LLMs) to determine the appropriate response, which is then converted back to voice via text-to-speech (TTS) engines and played back to the caller.</p>
            <p><strong className="text-foreground">Legality & Consent Mandates:</strong> Call recording is subject to strict local, state, and international wiretapping and privacy laws (e.g., "one-party consent" vs. "all-party consent" jurisdictions).</p>
            <p><strong className="text-foreground">The Warning Message:</strong> Unless explicitly waived by the Client under strict, verifiable legal advice, VyntaOne configures all AI voice agents to play a clear voice disclosure at the beginning of each call (e.g., "This call is being recorded for quality and scheduling purposes.").</p>
            <p><strong className="text-foreground">Client Liability:</strong> The Client holds ultimate responsibility for keeping this warning enabled and ensuring it complies with call recording laws in their respective market.</p>
            <p><strong className="text-foreground">Audio Storage & Security:</strong> Call recordings are encrypted both in transit (using TLS 1.3) and at rest (using AES-256 encryption). Recordings are stored securely in cloud-hosted environments and are accessible only to authorized personnel of the Client and VyntaOne for quality assurance and training purposes.</p>
          </div>
        </section>

        <section className="mt-14">
          <h2 className="font-display text-2xl md:text-3xl">Data Privacy Compliance Framework</h2>

          <h3 className="mt-8 text-lg font-medium text-foreground">General Data Protection Regulation (GDPR) — European Union</h3>
          <div className="mt-4 space-y-5 text-muted-foreground">
            <p>For individuals residing in the European Economic Area (EEA) and the United Kingdom (UK):</p>
            <p><strong className="text-foreground">Role Definition:</strong> VyntaOne operates as a Data Processor for Caller Data and as a Data Controller for Client Data.</p>
            <p><strong className="text-foreground">Legal Basis for Processing:</strong> We process Client Data to perform our contractual obligations under our Terms of Service. Caller Data is processed based on the Consent of the caller (provided via continuing the call after the disclosure message) and the Legitimate Interests of our Clients to automate their business reception services.</p>
            <p><strong className="text-foreground">Data Transfer Safeguards:</strong> Any cross-border data transfer outside the EEA is protected using Standard Contractual Clauses (SCCs) to ensure equivalent data protection.</p>
          </div>

          <h3 className="mt-8 text-lg font-medium text-foreground">California Consumer Privacy Act (CCPA) — United States</h3>
          <div className="mt-4 space-y-5 text-muted-foreground">
            <p>For residents of California:</p>
            <p><strong className="text-foreground">No Sale of Personal Information:</strong> VyntaOne does not sell, rent, or trade personal data or call records to third-party data brokers or advertisers.</p>
            <p><strong className="text-foreground">Right to Opt-Out & Access:</strong> California residents have the right to request access to the personal data we have collected about them, request deletion of that data, and opt out of any automated processing.</p>
          </div>

          <h3 className="mt-8 text-lg font-medium text-foreground">Children's Online Privacy Protection Act (COPPA) — United States</h3>
          <div className="mt-4 space-y-5 text-muted-foreground">
            <p><strong className="text-foreground">Age Restriction:</strong> VyntaOne's services are designed strictly for professional business-to-business (B2B) use. We do not intentionally or knowingly target, solicit, or collect personal information from children under the age of 13.</p>
            <p><strong className="text-foreground">Remediation:</strong> If we discover that personal data of a child under 13 has been inadvertently recorded or processed, we will immediately purge the record from our active databases and servers.</p>
          </div>
        </section>

        <section className="mt-14">
          <h2 className="font-display text-2xl md:text-3xl">Third-Party Data Processors and Service Integrations</h2>
          <div className="mt-6 space-y-5 text-muted-foreground">
            <p>To deliver our voice solutions, we share data with the following highly secure, compliant sub-processors:</p>
            <p><strong className="text-foreground">AI Synthesis and Language Models:</strong> OpenAI (GPT models), Anthropic (Claude models), and Deepgram. These partners maintain strict B2B privacy terms and do not use customer API data or call transcripts to train their foundational models.</p>
            <p><strong className="text-foreground">Telecommunication Infrastructure:</strong> Vapi, Twilio, and Retell AI (used strictly for call transport and processing).</p>
            <p><strong className="text-foreground">Scheduling Engines:</strong> Cal.com and Google Calendar (used to insert appointments into Client calendars).</p>
            <p><strong className="text-foreground">Merchant of Record & Payments:</strong> Paddle (handles checkout and payment data securely in compliance with PCI-DSS standards).</p>
          </div>
        </section>

        <section className="mt-14">
          <h2 className="font-display text-2xl md:text-3xl">Data Deletion and User Rights</h2>
          <div className="mt-6 space-y-5 text-muted-foreground">
            <p>We respect your right to control your personal data.</p>
            <p><strong className="text-foreground">Client Rights:</strong> Clients may view, edit, or delete their account details at any time by logging into their VyntaOne dashboard or contacting us directly.</p>
            <p><strong className="text-foreground">Caller Rights:</strong> Callers who wish to request a copy of their call recording, a copy of their conversation transcript, or the permanent deletion of their recorded call data from our systems must submit a formal request to our support desk.</p>
            <p><strong className="text-foreground">Processing Time:</strong> Once we verify the identity of the requesting party, we will process data deletion requests within thirty (30) calendar days.</p>
            <p>For all privacy-related inquiries, data access requests, or deletion petitions, please contact us at:</p>
            <p><strong className="text-foreground">Email:</strong> <a href="mailto:hello@vyntaone.com" className="text-primary underline underline-offset-4 transition hover:text-accent">hello@vyntaone.com</a></p>
            <p><strong className="text-foreground">Subject Line:</strong> Data Privacy Request</p>
          </div>
        </section>
      </article>

      <footer className="relative z-10 border-t border-border-subtle">
        <div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-8 px-6 py-12 md:flex-row md:items-center">
          <div>
            <div className="flex items-center gap-2">
              <span className="grid h-8 w-8 place-items-center rounded-full border border-border bg-surface-elevated">
                <span className="h-2 w-2 rounded-full bg-primary" />
              </span>
              <span className="font-display text-2xl">Vynta</span>
            </div>
            <p className="mt-3 max-w-xs text-sm text-muted-foreground">
              The 24/7 AI voice receptionist for high-growth businesses.
            </p>
          </div>
          <div className="flex flex-wrap gap-x-8 gap-y-2 text-sm text-muted-foreground">
            <Link to="/" className="transition hover:text-foreground">Home</Link>
            <Link to="/terms-of-service" className="transition hover:text-foreground">Terms</Link>
            <Link to="/privacy-policy" className="transition hover:text-foreground">Privacy</Link>
            <Link to="/refund-policy" className="transition hover:text-foreground">Refunds</Link>
          </div>
          <div className="font-mono text-xs text-muted-foreground">
            © {new Date().getFullYear()} Vynta. All rights reserved.
          </div>
        </div>
      </footer>
    </main>
  );
}
